# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\DATAANALYSE\PYTHON\PYQT\LightGCS\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gv_setter = QtWidgets.QGraphicsView(self.centralWidget)
        self.gv_setter.setGeometry(QtCore.QRect(0, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_setter.sizePolicy().hasHeightForWidth())
        self.gv_setter.setSizePolicy(sizePolicy)
        self.gv_setter.setMouseTracking(True)
        self.gv_setter.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gv_setter.setStyleSheet("border-image: url(:/side_btn/LightGCS_image/setter.png);")
        self.gv_setter.setObjectName("gv_setter")
        self.gv_logger = QtWidgets.QGraphicsView(self.centralWidget)
        self.gv_logger.setGeometry(QtCore.QRect(120, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_logger.sizePolicy().hasHeightForWidth())
        self.gv_logger.setSizePolicy(sizePolicy)
        self.gv_logger.setMouseTracking(True)
        self.gv_logger.setStyleSheet("border-image: url(:/side_btn/LightGCS_image/logger.png);")
        self.gv_logger.setObjectName("gv_logger")
        self.gv_monitor = QtWidgets.QGraphicsView(self.centralWidget)
        self.gv_monitor.setGeometry(QtCore.QRect(60, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_monitor.sizePolicy().hasHeightForWidth())
        self.gv_monitor.setSizePolicy(sizePolicy)
        self.gv_monitor.setMouseTracking(True)
        self.gv_monitor.setStyleSheet("border-image: url(:/side_btn/LightGCS_image/monitor.png);")
        self.gv_monitor.setObjectName("gv_monitor")
        self.gv_params = QtWidgets.QGraphicsView(self.centralWidget)
        self.gv_params.setGeometry(QtCore.QRect(180, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_params.sizePolicy().hasHeightForWidth())
        self.gv_params.setSizePolicy(sizePolicy)
        self.gv_params.setMouseTracking(True)
        self.gv_params.setStyleSheet("border-image: url(:/side_btn/LightGCS_image/params.png);")
        self.gv_params.setObjectName("gv_params")
        self.gv_exts = QtWidgets.QGraphicsView(self.centralWidget)
        self.gv_exts.setGeometry(QtCore.QRect(240, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_exts.sizePolicy().hasHeightForWidth())
        self.gv_exts.setSizePolicy(sizePolicy)
        self.gv_exts.setMouseTracking(True)
        self.gv_exts.setStyleSheet("border-image: url(:/side_btn/LightGCS_image/exts.png);")
        self.gv_exts.setObjectName("gv_exts")
        self.gv_about = QtWidgets.QGraphicsView(self.centralWidget)
        self.gv_about.setGeometry(QtCore.QRect(300, 0, 60, 60))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gv_about.sizePolicy().hasHeightForWidth())
        self.gv_about.setSizePolicy(sizePolicy)
        self.gv_about.setStyleSheet("border-image: url(:/side_btn/LightGCS_image/about.png);")
        self.gv_about.setObjectName("gv_about")
        self.stw_mainwindow = QtWidgets.QStackedWidget(self.centralWidget)
        self.stw_mainwindow.setGeometry(QtCore.QRect(3, 59, 1021, 711))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stw_mainwindow.sizePolicy().hasHeightForWidth())
        self.stw_mainwindow.setSizePolicy(sizePolicy)
        self.stw_mainwindow.setToolTip("")
        self.stw_mainwindow.setObjectName("stw_mainwindow")
        self.stw_setter = QtWidgets.QWidget()
        self.stw_setter.setObjectName("stw_setter")
        self.tb_console = QtWidgets.QTextBrowser(self.stw_setter)
        self.tb_console.setEnabled(True)
        self.tb_console.setGeometry(QtCore.QRect(0, 340, 265, 371))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tb_console.sizePolicy().hasHeightForWidth())
        self.tb_console.setSizePolicy(sizePolicy)
        self.tb_console.setReadOnly(False)
        self.tb_console.setObjectName("tb_console")
        self.gb_setting = QtWidgets.QGroupBox(self.stw_setter)
        self.gb_setting.setGeometry(QtCore.QRect(0, 10, 261, 321))
        self.gb_setting.setObjectName("gb_setting")
        self.pb_accel = QtWidgets.QPushButton(self.gb_setting)
        self.pb_accel.setGeometry(QtCore.QRect(20, 110, 211, 35))
        self.pb_accel.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_accel.setObjectName("pb_accel")
        self.pb_compass = QtWidgets.QPushButton(self.gb_setting)
        self.pb_compass.setGeometry(QtCore.QRect(20, 150, 211, 35))
        self.pb_compass.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_compass.setObjectName("pb_compass")
        self.pb_radio = QtWidgets.QPushButton(self.gb_setting)
        self.pb_radio.setGeometry(QtCore.QRect(20, 190, 211, 35))
        self.pb_radio.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_radio.setObjectName("pb_radio")
        self.pb_flt_mode = QtWidgets.QPushButton(self.gb_setting)
        self.pb_flt_mode.setGeometry(QtCore.QRect(20, 230, 211, 35))
        self.pb_flt_mode.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_flt_mode.setObjectName("pb_flt_mode")
        self.pb_pid = QtWidgets.QPushButton(self.gb_setting)
        self.pb_pid.setGeometry(QtCore.QRect(20, 270, 211, 35))
        self.pb_pid.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_pid.setObjectName("pb_pid")
        self.pb_firmware = QtWidgets.QPushButton(self.gb_setting)
        self.pb_firmware.setGeometry(QtCore.QRect(20, 30, 211, 35))
        self.pb_firmware.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_firmware.setObjectName("pb_firmware")
        self.pb_frame = QtWidgets.QPushButton(self.gb_setting)
        self.pb_frame.setGeometry(QtCore.QRect(20, 70, 211, 35))
        self.pb_frame.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_frame.setObjectName("pb_frame")
        self.stw_setter_sub = QtWidgets.QStackedWidget(self.stw_setter)
        self.stw_setter_sub.setGeometry(QtCore.QRect(280, 20, 731, 691))
        self.stw_setter_sub.setStyleSheet("")
        self.stw_setter_sub.setObjectName("stw_setter_sub")
        self.fw = QtWidgets.QWidget()
        self.fw.setObjectName("fw")
        self.fw_progressbar = QtWidgets.QProgressBar(self.fw)
        self.fw_progressbar.setGeometry(QtCore.QRect(10, 590, 721, 23))
        self.fw_progressbar.setProperty("value", 0)
        self.fw_progressbar.setObjectName("fw_progressbar")
        self.fw_upload_state = QtWidgets.QLabel(self.fw)
        self.fw_upload_state.setGeometry(QtCore.QRect(10, 550, 701, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fw_upload_state.setFont(font)
        self.fw_upload_state.setObjectName("fw_upload_state")
        self.gb_fw_online = QtWidgets.QGroupBox(self.fw)
        self.gb_fw_online.setGeometry(QtCore.QRect(0, 0, 751, 391))
        self.gb_fw_online.setObjectName("gb_fw_online")
        self.gv_wired_copter = QtWidgets.QGraphicsView(self.gb_fw_online)
        self.gv_wired_copter.setGeometry(QtCore.QRect(10, 30, 231, 161))
        self.gv_wired_copter.setObjectName("gv_wired_copter")
        self.gv_copter = QtWidgets.QGraphicsView(self.gb_fw_online)
        self.gv_copter.setGeometry(QtCore.QRect(10, 210, 231, 161))
        self.gv_copter.setObjectName("gv_copter")
        self.gv_wired_copter_3 = QtWidgets.QGraphicsView(self.gb_fw_online)
        self.gv_wired_copter_3.setGeometry(QtCore.QRect(510, 30, 221, 161))
        self.gv_wired_copter_3.setObjectName("gv_wired_copter_3")
        self.gv_wired_copter_4 = QtWidgets.QGraphicsView(self.gb_fw_online)
        self.gv_wired_copter_4.setGeometry(QtCore.QRect(510, 210, 221, 161))
        self.gv_wired_copter_4.setObjectName("gv_wired_copter_4")
        self.gv_fixed_wing = QtWidgets.QGraphicsView(self.gb_fw_online)
        self.gv_fixed_wing.setGeometry(QtCore.QRect(260, 30, 231, 161))
        self.gv_fixed_wing.setObjectName("gv_fixed_wing")
        self.gv_tiltrotor = QtWidgets.QGraphicsView(self.gb_fw_online)
        self.gv_tiltrotor.setGeometry(QtCore.QRect(260, 210, 231, 161))
        self.gv_tiltrotor.setObjectName("gv_tiltrotor")
        self.gb_fw_load = QtWidgets.QGroupBox(self.fw)
        self.gb_fw_load.setGeometry(QtCore.QRect(0, 400, 751, 91))
        self.gb_fw_load.setObjectName("gb_fw_load")
        self.comboBox = QtWidgets.QComboBox(self.gb_fw_load)
        self.comboBox.setGeometry(QtCore.QRect(90, 30, 271, 41))
        self.comboBox.setObjectName("comboBox")
        self.pb_custom_fw = QtWidgets.QPushButton(self.gb_fw_load)
        self.pb_custom_fw.setGeometry(QtCore.QRect(520, 20, 201, 61))
        self.pb_custom_fw.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.pb_custom_fw.setObjectName("pb_custom_fw")
        self.label_3 = QtWidgets.QLabel(self.gb_fw_load)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 61, 31))
        self.label_3.setObjectName("label_3")
        self.stw_setter_sub.addWidget(self.fw)
        self.frame = QtWidgets.QWidget()
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(140, 200, 291, 121))
        self.label.setObjectName("label")
        self.stw_setter_sub.addWidget(self.frame)
        self.accel = QtWidgets.QWidget()
        self.accel.setObjectName("accel")
        self.textEdit_5 = QtWidgets.QTextEdit(self.accel)
        self.textEdit_5.setGeometry(QtCore.QRect(150, 200, 351, 87))
        self.textEdit_5.setObjectName("textEdit_5")
        self.stw_setter_sub.addWidget(self.accel)
        self.compass = QtWidgets.QWidget()
        self.compass.setObjectName("compass")
        self.textEdit_6 = QtWidgets.QTextEdit(self.compass)
        self.textEdit_6.setGeometry(QtCore.QRect(150, 230, 361, 87))
        self.textEdit_6.setObjectName("textEdit_6")
        self.stw_setter_sub.addWidget(self.compass)
        self.rc = QtWidgets.QWidget()
        self.rc.setObjectName("rc")
        self.textEdit_7 = QtWidgets.QTextEdit(self.rc)
        self.textEdit_7.setGeometry(QtCore.QRect(200, 220, 321, 87))
        self.textEdit_7.setObjectName("textEdit_7")
        self.stw_setter_sub.addWidget(self.rc)
        self.fltMode = QtWidgets.QWidget()
        self.fltMode.setObjectName("fltMode")
        self.textEdit_9 = QtWidgets.QTextEdit(self.fltMode)
        self.textEdit_9.setGeometry(QtCore.QRect(180, 210, 291, 87))
        self.textEdit_9.setObjectName("textEdit_9")
        self.stw_setter_sub.addWidget(self.fltMode)
        self.pid = QtWidgets.QWidget()
        self.pid.setObjectName("pid")
        self.textEdit_8 = QtWidgets.QTextEdit(self.pid)
        self.textEdit_8.setGeometry(QtCore.QRect(170, 220, 301, 87))
        self.textEdit_8.setObjectName("textEdit_8")
        self.stw_setter_sub.addWidget(self.pid)
        self.stw_mainwindow.addWidget(self.stw_setter)
        self.stw_status = QtWidgets.QWidget()
        self.stw_status.setObjectName("stw_status")
        self.textEdit_2 = QtWidgets.QTextEdit(self.stw_status)
        self.textEdit_2.setGeometry(QtCore.QRect(240, 280, 421, 87))
        self.textEdit_2.setObjectName("textEdit_2")
        self.stw_mainwindow.addWidget(self.stw_status)
        self.stw_logger = QtWidgets.QWidget()
        self.stw_logger.setObjectName("stw_logger")
        self.textEdit = QtWidgets.QTextEdit(self.stw_logger)
        self.textEdit.setGeometry(QtCore.QRect(250, 280, 421, 87))
        self.textEdit.setObjectName("textEdit")
        self.stw_mainwindow.addWidget(self.stw_logger)
        self.stw_params = QtWidgets.QWidget()
        self.stw_params.setObjectName("stw_params")
        self.pb_params_read = QtWidgets.QPushButton(self.stw_params)
        self.pb_params_read.setGeometry(QtCore.QRect(0, 390, 81, 51))
        self.pb_params_read.setObjectName("pb_params_read")
        self.pb_params_tree = QtWidgets.QPushButton(self.stw_params)
        self.pb_params_tree.setGeometry(QtCore.QRect(0, 240, 81, 51))
        self.pb_params_tree.setObjectName("pb_params_tree")
        self.pb_params_set = QtWidgets.QPushButton(self.stw_params)
        self.pb_params_set.setGeometry(QtCore.QRect(0, 290, 81, 51))
        self.pb_params_set.setObjectName("pb_params_set")
        self.pb_params_save = QtWidgets.QPushButton(self.stw_params)
        self.pb_params_save.setGeometry(QtCore.QRect(0, 340, 81, 51))
        self.pb_params_save.setObjectName("pb_params_save")
        self.stw_params_sub = QtWidgets.QStackedWidget(self.stw_params)
        self.stw_params_sub.setGeometry(QtCore.QRect(80, 20, 931, 691))
        self.stw_params_sub.setObjectName("stw_params_sub")
        self.stw_params_table = QtWidgets.QWidget()
        self.stw_params_table.setObjectName("stw_params_table")
        self.tv_params = QtWidgets.QTableView(self.stw_params_table)
        self.tv_params.setGeometry(QtCore.QRect(0, 0, 930, 690))
        self.tv_params.setAutoFillBackground(True)
        self.tv_params.setStyleSheet("")
        self.tv_params.setSortingEnabled(False)
        self.tv_params.setObjectName("tv_params")
        self.tv_params.horizontalHeader().setHighlightSections(False)
        self.tv_params.horizontalHeader().setSortIndicatorShown(False)
        self.tv_params.horizontalHeader().setStretchLastSection(False)
        self.stw_params_sub.addWidget(self.stw_params_table)
        self.stw_params_tree = QtWidgets.QWidget()
        self.stw_params_tree.setObjectName("stw_params_tree")
        self.label_2 = QtWidgets.QLabel(self.stw_params_tree)
        self.label_2.setGeometry(QtCore.QRect(420, 640, 91, 16))
        self.label_2.setObjectName("label_2")
        self.stw_params_sub.addWidget(self.stw_params_tree)
        self.pb_params_table = QtWidgets.QPushButton(self.stw_params)
        self.pb_params_table.setGeometry(QtCore.QRect(0, 190, 81, 51))
        self.pb_params_table.setObjectName("pb_params_table")
        self.stw_mainwindow.addWidget(self.stw_params)
        self.stw_exts = QtWidgets.QWidget()
        self.stw_exts.setObjectName("stw_exts")
        self.rb_xrotor_calc = QtWidgets.QRadioButton(self.stw_exts)
        self.rb_xrotor_calc.setGeometry(QtCore.QRect(10, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_xrotor_calc.setFont(font)
        self.rb_xrotor_calc.setCheckable(True)
        self.rb_xrotor_calc.setChecked(False)
        self.rb_xrotor_calc.setObjectName("rb_xrotor_calc")
        self.stw_exts_sub = QtWidgets.QStackedWidget(self.stw_exts)
        self.stw_exts_sub.setGeometry(QtCore.QRect(190, 10, 831, 701))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.stw_exts_sub.setFont(font)
        self.stw_exts_sub.setObjectName("stw_exts_sub")
        self.xrotor_calc = QtWidgets.QWidget()
        self.xrotor_calc.setObjectName("xrotor_calc")
        self.xrotor_ecalc = QtWidgets.QGroupBox(self.xrotor_calc)
        self.xrotor_ecalc.setGeometry(QtCore.QRect(10, 0, 801, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.xrotor_ecalc.setFont(font)
        self.xrotor_ecalc.setObjectName("xrotor_ecalc")
        self.label_4 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_5.setGeometry(QtCore.QRect(170, 20, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_7.setGeometry(QtCore.QRect(250, 60, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_8.setGeometry(QtCore.QRect(250, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.cb_copter_frame = QtWidgets.QComboBox(self.xrotor_ecalc)
        self.cb_copter_frame.setEnabled(True)
        self.cb_copter_frame.setGeometry(QtCore.QRect(210, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_copter_frame.setFont(font)
        self.cb_copter_frame.setEditable(False)
        self.cb_copter_frame.setObjectName("cb_copter_frame")
        self.cb_motor_type = QtWidgets.QComboBox(self.xrotor_ecalc)
        self.cb_motor_type.setGeometry(QtCore.QRect(50, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_motor_type.setFont(font)
        self.cb_motor_type.setEditable(False)
        self.cb_motor_type.setObjectName("cb_motor_type")
        self.cb_prop_type = QtWidgets.QComboBox(self.xrotor_ecalc)
        self.cb_prop_type.setGeometry(QtCore.QRect(300, 60, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_prop_type.setFont(font)
        self.cb_prop_type.setEditable(False)
        self.cb_prop_type.setObjectName("cb_prop_type")
        self.le_weight = QtWidgets.QLineEdit(self.xrotor_ecalc)
        self.le_weight.setGeometry(QtCore.QRect(50, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_weight.setFont(font)
        self.le_weight.setText("")
        self.le_weight.setObjectName("le_weight")
        self.le_battery_capacity = QtWidgets.QLineEdit(self.xrotor_ecalc)
        self.le_battery_capacity.setGeometry(QtCore.QRect(300, 100, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_battery_capacity.setFont(font)
        self.le_battery_capacity.setObjectName("le_battery_capacity")
        self.pb_xrotor_calc = QtWidgets.QPushButton(self.xrotor_ecalc)
        self.pb_xrotor_calc.setGeometry(QtCore.QRect(670, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_xrotor_calc.setFont(font)
        self.pb_xrotor_calc.setObjectName("pb_xrotor_calc")
        self.pb_xrotor_reset = QtWidgets.QPushButton(self.xrotor_ecalc)
        self.pb_xrotor_reset.setGeometry(QtCore.QRect(510, 140, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pb_xrotor_reset.setFont(font)
        self.pb_xrotor_reset.setObjectName("pb_xrotor_reset")
        self.label_9 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_9.setGeometry(QtCore.QRect(10, 100, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.cb_volt = QtWidgets.QComboBox(self.xrotor_ecalc)
        self.cb_volt.setGeometry(QtCore.QRect(50, 100, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_volt.setFont(font)
        self.cb_volt.setEditable(False)
        self.cb_volt.setObjectName("cb_volt")
        self.label_10 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_10.setGeometry(QtCore.QRect(430, 100, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.le_flight_height = QtWidgets.QLineEdit(self.xrotor_ecalc)
        self.le_flight_height.setGeometry(QtCore.QRect(560, 20, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_flight_height.setFont(font)
        self.le_flight_height.setObjectName("le_flight_height")
        self.label_11 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_11.setGeometry(QtCore.QRect(520, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.le_capacity_residual = QtWidgets.QLineEdit(self.xrotor_ecalc)
        self.le_capacity_residual.setGeometry(QtCore.QRect(560, 100, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_capacity_residual.setFont(font)
        self.le_capacity_residual.setObjectName("le_capacity_residual")
        self.label_12 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_12.setGeometry(QtCore.QRect(480, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_13.setGeometry(QtCore.QRect(620, 100, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.le_uav_axisDist = QtWidgets.QLineEdit(self.xrotor_ecalc)
        self.le_uav_axisDist.setGeometry(QtCore.QRect(400, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_uav_axisDist.setFont(font)
        self.le_uav_axisDist.setText("")
        self.le_uav_axisDist.setObjectName("le_uav_axisDist")
        self.label_14 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_14.setGeometry(QtCore.QRect(360, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_15.setGeometry(QtCore.QRect(140, 20, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_16.setGeometry(QtCore.QRect(480, 20, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_17.setGeometry(QtCore.QRect(630, 20, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_18.setGeometry(QtCore.QRect(760, 20, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.xrotor_ecalc)
        self.label_19.setGeometry(QtCore.QRect(670, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.le_ground_temperature = QtWidgets.QLineEdit(self.xrotor_ecalc)
        self.le_ground_temperature.setGeometry(QtCore.QRect(710, 20, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.le_ground_temperature.setFont(font)
        self.le_ground_temperature.setObjectName("le_ground_temperature")
        self.stw_exts_sub.addWidget(self.xrotor_calc)
        self.fixedwing_calc = QtWidgets.QWidget()
        self.fixedwing_calc.setObjectName("fixedwing_calc")
        self.stw_exts_sub.addWidget(self.fixedwing_calc)
        self.tiltrotor_calc = QtWidgets.QWidget()
        self.tiltrotor_calc.setObjectName("tiltrotor_calc")
        self.stw_exts_sub.addWidget(self.tiltrotor_calc)
        self.rotor_db = QtWidgets.QWidget()
        self.rotor_db.setObjectName("rotor_db")
        self.tw_motor_db = QtWidgets.QTabWidget(self.rotor_db)
        self.tw_motor_db.setGeometry(QtCore.QRect(0, 0, 831, 701))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tw_motor_db.setFont(font)
        self.tw_motor_db.setObjectName("tw_motor_db")
        self.tw_insert_data_bat = QtWidgets.QWidget()
        self.tw_insert_data_bat.setObjectName("tw_insert_data_bat")
        self.pb_motor_db_file_insert = QtWidgets.QPushButton(self.tw_insert_data_bat)
        self.pb_motor_db_file_insert.setGeometry(QtCore.QRect(370, 260, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_motor_db_file_insert.setFont(font)
        self.pb_motor_db_file_insert.setObjectName("pb_motor_db_file_insert")
        self.pb_motor_db_file_remove = QtWidgets.QPushButton(self.tw_insert_data_bat)
        self.pb_motor_db_file_remove.setGeometry(QtCore.QRect(370, 300, 93, 28))
        self.pb_motor_db_file_remove.setObjectName("pb_motor_db_file_remove")
        self.pb_motor_db_insert_confirm = QtWidgets.QPushButton(self.tw_insert_data_bat)
        self.pb_motor_db_insert_confirm.setGeometry(QtCore.QRect(350, 420, 141, 41))
        self.pb_motor_db_insert_confirm.setObjectName("pb_motor_db_insert_confirm")
        self.label_25 = QtWidgets.QLabel(self.tw_insert_data_bat)
        self.label_25.setGeometry(QtCore.QRect(120, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.pb_motor_db_file_read = QtWidgets.QPushButton(self.tw_insert_data_bat)
        self.pb_motor_db_file_read.setGeometry(QtCore.QRect(370, 220, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pb_motor_db_file_read.setFont(font)
        self.pb_motor_db_file_read.setObjectName("pb_motor_db_file_read")
        self.label_26 = QtWidgets.QLabel(self.tw_insert_data_bat)
        self.label_26.setGeometry(QtCore.QRect(620, 30, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tw_insert_data_bat)
        self.label_27.setGeometry(QtCore.QRect(10, 590, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_motor_db_path = QtWidgets.QLabel(self.tw_insert_data_bat)
        self.label_motor_db_path.setGeometry(QtCore.QRect(110, 590, 711, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_motor_db_path.setFont(font)
        self.label_motor_db_path.setText("")
        self.label_motor_db_path.setObjectName("label_motor_db_path")
        self.pb_motor_db_doc_select = QtWidgets.QPushButton(self.tw_insert_data_bat)
        self.pb_motor_db_doc_select.setGeometry(QtCore.QRect(100, 550, 151, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_motor_db_doc_select.setFont(font)
        self.pb_motor_db_doc_select.setObjectName("pb_motor_db_doc_select")
        self.lw_motor_test_files = QtWidgets.QListWidget(self.tw_insert_data_bat)
        self.lw_motor_test_files.setGeometry(QtCore.QRect(30, 60, 281, 481))
        self.lw_motor_test_files.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lw_motor_test_files.setObjectName("lw_motor_test_files")
        self.lw_motor_db_files = QtWidgets.QListWidget(self.tw_insert_data_bat)
        self.lw_motor_db_files.setGeometry(QtCore.QRect(520, 60, 281, 481))
        self.lw_motor_db_files.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.lw_motor_db_files.setObjectName("lw_motor_db_files")
        self.label_28 = QtWidgets.QLabel(self.tw_insert_data_bat)
        self.label_28.setGeometry(QtCore.QRect(10, 630, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_db_dml_status = QtWidgets.QLabel(self.tw_insert_data_bat)
        self.label_db_dml_status.setGeometry(QtCore.QRect(110, 630, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_db_dml_status.setFont(font)
        self.label_db_dml_status.setStyleSheet("color: rgb(85, 170, 0);")
        self.label_db_dml_status.setText("")
        self.label_db_dml_status.setObjectName("label_db_dml_status")
        self.tw_motor_db.addTab(self.tw_insert_data_bat, "")
        self.tw_data_sql = QtWidgets.QWidget()
        self.tw_data_sql.setObjectName("tw_data_sql")
        self.label_20 = QtWidgets.QLabel(self.tw_data_sql)
        self.label_20.setGeometry(QtCore.QRect(30, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.cb_motor_db_productor = QtWidgets.QComboBox(self.tw_data_sql)
        self.cb_motor_db_productor.setGeometry(QtCore.QRect(10, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motor_db_productor.setFont(font)
        self.cb_motor_db_productor.setObjectName("cb_motor_db_productor")
        self.cb_motor_db_type = QtWidgets.QComboBox(self.tw_data_sql)
        self.cb_motor_db_type.setGeometry(QtCore.QRect(130, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motor_db_type.setFont(font)
        self.cb_motor_db_type.setObjectName("cb_motor_db_type")
        self.label_21 = QtWidgets.QLabel(self.tw_data_sql)
        self.label_21.setGeometry(QtCore.QRect(150, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.cb_motor_db_kv = QtWidgets.QComboBox(self.tw_data_sql)
        self.cb_motor_db_kv.setGeometry(QtCore.QRect(250, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motor_db_kv.setFont(font)
        self.cb_motor_db_kv.setObjectName("cb_motor_db_kv")
        self.label_22 = QtWidgets.QLabel(self.tw_data_sql)
        self.label_22.setGeometry(QtCore.QRect(280, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.cb_motor_db_propeller = QtWidgets.QComboBox(self.tw_data_sql)
        self.cb_motor_db_propeller.setGeometry(QtCore.QRect(370, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motor_db_propeller.setFont(font)
        self.cb_motor_db_propeller.setObjectName("cb_motor_db_propeller")
        self.label_23 = QtWidgets.QLabel(self.tw_data_sql)
        self.label_23.setGeometry(QtCore.QRect(400, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.pb_motor_data_sql = QtWidgets.QPushButton(self.tw_data_sql)
        self.pb_motor_data_sql.setGeometry(QtCore.QRect(730, 7, 93, 71))
        self.pb_motor_data_sql.setObjectName("pb_motor_data_sql")
        self.cb_motor_db_volt = QtWidgets.QComboBox(self.tw_data_sql)
        self.cb_motor_db_volt.setGeometry(QtCore.QRect(490, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motor_db_volt.setFont(font)
        self.cb_motor_db_volt.setObjectName("cb_motor_db_volt")
        self.label_24 = QtWidgets.QLabel(self.tw_data_sql)
        self.label_24.setGeometry(QtCore.QRect(510, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.tv_motor_data = QtWidgets.QTableView(self.tw_data_sql)
        self.tv_motor_data.setEnabled(True)
        self.tv_motor_data.setGeometry(QtCore.QRect(0, 80, 825, 591))
        self.tv_motor_data.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tv_motor_data.setObjectName("tv_motor_data")
        self.tw_motor_db.addTab(self.tw_data_sql, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tv_motor_tables = QtWidgets.QTableView(self.tab)
        self.tv_motor_tables.setGeometry(QtCore.QRect(0, 80, 821, 591))
        self.tv_motor_tables.setDragEnabled(True)
        self.tv_motor_tables.setObjectName("tv_motor_tables")
        self.tv_motor_tables.horizontalHeader().setCascadingSectionResizes(True)
        self.cb_motor_tables = QtWidgets.QComboBox(self.tab)
        self.cb_motor_tables.setGeometry(QtCore.QRect(450, 40, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_motor_tables.setFont(font)
        self.cb_motor_tables.setObjectName("cb_motor_tables")
        self.label_29 = QtWidgets.QLabel(self.tab)
        self.label_29.setGeometry(QtCore.QRect(500, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.pb_motor_db_update = QtWidgets.QPushButton(self.tab)
        self.pb_motor_db_update.setGeometry(QtCore.QRect(720, 10, 93, 61))
        self.pb_motor_db_update.setObjectName("pb_motor_db_update")
        self.pb_motor_table_show = QtWidgets.QPushButton(self.tab)
        self.pb_motor_table_show.setGeometry(QtCore.QRect(620, 10, 93, 61))
        self.pb_motor_table_show.setObjectName("pb_motor_table_show")
        self.pb_motor_db_insert_row = QtWidgets.QPushButton(self.tab)
        self.pb_motor_db_insert_row.setGeometry(QtCore.QRect(10, 40, 93, 28))
        self.pb_motor_db_insert_row.setObjectName("pb_motor_db_insert_row")
        self.pb_motor_db_delete_row = QtWidgets.QPushButton(self.tab)
        self.pb_motor_db_delete_row.setGeometry(QtCore.QRect(120, 40, 93, 28))
        self.pb_motor_db_delete_row.setObjectName("pb_motor_db_delete_row")
        self.tw_motor_db.addTab(self.tab, "")
        self.stw_exts_sub.addWidget(self.rotor_db)
        self.rb_fixedwing_calc = QtWidgets.QRadioButton(self.stw_exts)
        self.rb_fixedwing_calc.setGeometry(QtCore.QRect(10, 90, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_fixedwing_calc.setFont(font)
        self.rb_fixedwing_calc.setCheckable(True)
        self.rb_fixedwing_calc.setChecked(False)
        self.rb_fixedwing_calc.setObjectName("rb_fixedwing_calc")
        self.rb_tiltrotor_calc = QtWidgets.QRadioButton(self.stw_exts)
        self.rb_tiltrotor_calc.setGeometry(QtCore.QRect(10, 140, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_tiltrotor_calc.setFont(font)
        self.rb_tiltrotor_calc.setCheckable(True)
        self.rb_tiltrotor_calc.setChecked(False)
        self.rb_tiltrotor_calc.setObjectName("rb_tiltrotor_calc")
        self.rb_rotor_database = QtWidgets.QRadioButton(self.stw_exts)
        self.rb_rotor_database.setGeometry(QtCore.QRect(10, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.rb_rotor_database.setFont(font)
        self.rb_rotor_database.setCheckable(True)
        self.rb_rotor_database.setChecked(False)
        self.rb_rotor_database.setObjectName("rb_rotor_database")
        self.stw_mainwindow.addWidget(self.stw_exts)
        self.cb_comm_name = QtWidgets.QComboBox(self.centralWidget)
        self.cb_comm_name.setGeometry(QtCore.QRect(780, 0, 135, 30))
        self.cb_comm_name.setObjectName("cb_comm_name")
        self.cb_comm_rate = QtWidgets.QComboBox(self.centralWidget)
        self.cb_comm_rate.setGeometry(QtCore.QRect(780, 35, 135, 30))
        self.cb_comm_rate.setObjectName("cb_comm_rate")
        self.pb_connection = QtWidgets.QPushButton(self.centralWidget)
        self.pb_connection.setGeometry(QtCore.QRect(920, 0, 101, 66))
        self.pb_connection.setStyleSheet("background-color: rgb(204, 255, 102);")
        self.pb_connection.setObjectName("pb_connection")
        self.label_mode = QtWidgets.QLabel(self.centralWidget)
        self.label_mode.setGeometry(QtCore.QRect(370, 10, 181, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_mode.sizePolicy().hasHeightForWidth())
        self.label_mode.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_mode.setFont(font)
        self.label_mode.setStyleSheet("color: rgb(85, 0, 255);")
        self.label_mode.setText("")
        self.label_mode.setAlignment(QtCore.Qt.AlignCenter)
        self.label_mode.setObjectName("label_mode")
        self.label_armed = QtWidgets.QLabel(self.centralWidget)
        self.label_armed.setGeometry(QtCore.QRect(560, 10, 181, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_armed.sizePolicy().hasHeightForWidth())
        self.label_armed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_armed.setFont(font)
        self.label_armed.setStyleSheet("color: rgb(85, 0, 255);")
        self.label_armed.setText("")
        self.label_armed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_armed.setObjectName("label_armed")
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.stw_mainwindow.setCurrentIndex(4)
        self.stw_setter_sub.setCurrentIndex(0)
        self.stw_params_sub.setCurrentIndex(0)
        self.stw_exts_sub.setCurrentIndex(3)
        self.tw_motor_db.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LightGCS"))
        self.gb_setting.setTitle(_translate("MainWindow", "CALIBRATING"))
        self.pb_accel.setText(_translate("MainWindow", "Accelerator"))
        self.pb_compass.setText(_translate("MainWindow", "Magnetic"))
        self.pb_radio.setText(_translate("MainWindow", "Radio Controller"))
        self.pb_flt_mode.setText(_translate("MainWindow", "Flight Mode"))
        self.pb_pid.setText(_translate("MainWindow", "PID"))
        self.pb_firmware.setText(_translate("MainWindow", "Firmware"))
        self.pb_frame.setText(_translate("MainWindow", "Frame Type"))
        self.fw_upload_state.setText(_translate("MainWindow", "Firmware Upload Status"))
        self.gb_fw_online.setTitle(_translate("MainWindow", "Firmware Online"))
        self.gb_fw_load.setTitle(_translate("MainWindow", "Firmware Local"))
        self.pb_custom_fw.setText(_translate("MainWindow", "Custom Firmware"))
        self.label_3.setText(_translate("MainWindow", "本地固件"))
        self.label.setText(_translate("MainWindow", "Frame Type"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">加速度计校准</p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">罗盘校准</p></body></html>"))
        self.textEdit_7.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">遥控校准</p></body></html>"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">飞行模式设置</p></body></html>"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">PID调节</p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">飞机状态监控窗</p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">日志分析窗</p></body></html>"))
        self.pb_params_read.setText(_translate("MainWindow", "读取参数"))
        self.pb_params_tree.setText(_translate("MainWindow", "分组显示"))
        self.pb_params_set.setText(_translate("MainWindow", "写入参数"))
        self.pb_params_save.setText(_translate("MainWindow", "保存参数"))
        self.label_2.setText(_translate("MainWindow", "Tree View"))
        self.pb_params_table.setText(_translate("MainWindow", "列表显示"))
        self.rb_xrotor_calc.setText(_translate("MainWindow", "多旋翼机评估"))
        self.xrotor_ecalc.setTitle(_translate("MainWindow", "参数"))
        self.label_4.setText(_translate("MainWindow", "重量"))
        self.label_5.setText(_translate("MainWindow", "机型"))
        self.label_6.setText(_translate("MainWindow", "电机"))
        self.label_7.setText(_translate("MainWindow", "桨"))
        self.label_8.setText(_translate("MainWindow", "容量"))
        self.cb_copter_frame.setToolTip(_translate("MainWindow", "旋翼机类型，如4轴、6轴，..."))
        self.cb_motor_type.setToolTip(_translate("MainWindow", "电机类型"))
        self.cb_prop_type.setToolTip(_translate("MainWindow", "螺旋桨尺寸"))
        self.le_weight.setToolTip(_translate("MainWindow", "飞机总重"))
        self.le_battery_capacity.setToolTip(_translate("MainWindow", "电池容量"))
        self.le_battery_capacity.setText(_translate("MainWindow", "10000"))
        self.pb_xrotor_calc.setToolTip(_translate("MainWindow", "评估旋翼机性能"))
        self.pb_xrotor_calc.setText(_translate("MainWindow", "解析"))
        self.pb_xrotor_reset.setToolTip(_translate("MainWindow", "清空输入及选型"))
        self.pb_xrotor_reset.setText(_translate("MainWindow", "清空"))
        self.label_9.setText(_translate("MainWindow", "电压"))
        self.cb_volt.setToolTip(_translate("MainWindow", "电机工作电压"))
        self.label_10.setText(_translate("MainWindow", "mAh"))
        self.le_flight_height.setToolTip(_translate("MainWindow", "无人机飞行高度，默认100米"))
        self.le_flight_height.setText(_translate("MainWindow", "100"))
        self.label_11.setText(_translate("MainWindow", "飞高"))
        self.le_capacity_residual.setToolTip(_translate("MainWindow", "电池剩余电量, 默认15%"))
        self.le_capacity_residual.setText(_translate("MainWindow", "15"))
        self.label_12.setText(_translate("MainWindow", "放电下限"))
        self.label_13.setText(_translate("MainWindow", "%"))
        self.le_uav_axisDist.setToolTip(_translate("MainWindow", "旋翼机轴距"))
        self.label_14.setText(_translate("MainWindow", "轴距"))
        self.label_15.setText(_translate("MainWindow", "g"))
        self.label_16.setText(_translate("MainWindow", "mm"))
        self.label_17.setText(_translate("MainWindow", "m"))
        self.label_18.setText(_translate("MainWindow", "℃"))
        self.label_19.setText(_translate("MainWindow", "温度"))
        self.le_ground_temperature.setToolTip(_translate("MainWindow", "地面环境温度"))
        self.le_ground_temperature.setText(_translate("MainWindow", "25"))
        self.pb_motor_db_file_insert.setText(_translate("MainWindow", "插入"))
        self.pb_motor_db_file_remove.setText(_translate("MainWindow", "移除"))
        self.pb_motor_db_insert_confirm.setText(_translate("MainWindow", "清除数据库"))
        self.label_25.setText(_translate("MainWindow", "待加入文件"))
        self.pb_motor_db_file_read.setText(_translate("MainWindow", "读取"))
        self.label_26.setText(_translate("MainWindow", "已加入文件"))
        self.label_27.setText(_translate("MainWindow", "文件目录"))
        self.pb_motor_db_doc_select.setText(_translate("MainWindow", "目录/文件"))
        self.label_28.setText(_translate("MainWindow", "执行状态"))
        self.tw_motor_db.setTabText(self.tw_motor_db.indexOf(self.tw_insert_data_bat), _translate("MainWindow", "插入数据"))
        self.label_20.setText(_translate("MainWindow", "电机厂商"))
        self.label_21.setText(_translate("MainWindow", "电机型号"))
        self.label_22.setText(_translate("MainWindow", "Kv值"))
        self.label_23.setText(_translate("MainWindow", "桨尺寸"))
        self.pb_motor_data_sql.setText(_translate("MainWindow", "查询"))
        self.label_24.setText(_translate("MainWindow", "工作电压"))
        self.tw_motor_db.setTabText(self.tw_motor_db.indexOf(self.tw_data_sql), _translate("MainWindow", "检索数据"))
        self.label_29.setText(_translate("MainWindow", "数据表"))
        self.pb_motor_db_update.setText(_translate("MainWindow", "更新"))
        self.pb_motor_table_show.setText(_translate("MainWindow", "显示"))
        self.pb_motor_db_insert_row.setText(_translate("MainWindow", "插入"))
        self.pb_motor_db_delete_row.setText(_translate("MainWindow", "删除"))
        self.tw_motor_db.setTabText(self.tw_motor_db.indexOf(self.tab), _translate("MainWindow", "修改数据"))
        self.rb_fixedwing_calc.setText(_translate("MainWindow", "固定翼机评估"))
        self.rb_tiltrotor_calc.setText(_translate("MainWindow", "倾旋翼机评估"))
        self.rb_rotor_database.setText(_translate("MainWindow", "电机数据库"))
        self.pb_connection.setText(_translate("MainWindow", "CONNECT"))

import LightGCS_image_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

